#!/usr/bin/env python

s3_patterns = {
    "making and evolving agreements": [
        "resolve objections",
        "driver",
        "evaluating decisions",
        "proposal forming",
        "consent decision making",
        "strategy",
        "objections",
        "agreements",
        "intended outcome",
        "deliverables",
        "evaluation criteria",
        "those affected decide",
        "qualifying drivers",
        "circle",
    ],
    "navigation": [
        "navigation backlog",
        "navigation meeting",
        "navigation via tensions",
    ],
    "effective meetings": [
        "meeting facilitation",
        "S3 facilitator",
        "secretary",
        "meetingevaluation",
        "rounds",
        "logbook",
        "logbook keeper",
        "artful participation",
    ],
    "coordinating work": [
        "retrospective",
        "pull-system for work",
        "visualize work",
        "prioritized backlog",
        "coordinator role",
        "daily standup",
        "coordination meeting",
        "planning and review meetings",
    ],
    "building organizations": [
        "organizing in circles",
        "open systems",
        "subset drivers",
        "align flow",
        "domains",
    ],
    "roles": [
        "role descriptions",
        "role selection",
        "effectiveness review",
        "development plan",
        "support roles",
    ],
    "organizational structure": [
        "double linking",
        "service circle",
        "nested circle",
        "delegate circle",
        "backbone organization",
        "fractal organization",
        "peach organization",
        "double-linked hierarchy",
        "helping circle",
        "role: representative",
        "coordination circle",
    ],
    "alignment": [
        "adopt S3 principles",
        "transparent salary",
        "contracting and accountability",
        "agree on values ",
        "bylaws",
        "linking",
    ],
    "bringing in S3 patterns": [
        "pull-system for organizational change",
        "adapt patterns to context",
        "open S3 adoption",
        "be the change",
        "continuous improvement of work process",
    ]
}